name: Preview
on: [push, pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip1-threads

      - name: Install Rust target
        run: rustup target add wasm32-wasip1-threads

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Publish preview
        run: |
          # Copy native binaries to main package directory for publishing
          cp ./crates/node/npm/darwin-arm64/tailwindcss-oxide.darwin-arm64.node ./crates/node/
          cp ./crates/node/npm/wasm32-wasi/tailwindcss-oxide.wasm32-wasi.wasm ./crates/node/
          cp ./crates/node/npm/wasm32-wasi/tailwindcss-oxide.wasi.cjs ./crates/node/
          
          # Publish main package with native binaries included
          pnpx pkg-pr-new publish './crates/node' --template './crates/node/'